title: "From code to boardroom"
description: "Code to Boardroom explores the intersection of technology, leadership, and business, offering insights from my experience growing as a technology leader."
permalink: ':title/'
baseurl: "/"
url: "http://stew.andersonuk.org"
author: "Stew Anderson"
author-img: "stew-anderson.jpeg"
about-author: "I'm Stew, a developer turned technology leader, I swapped commits for conversations and I'm sharing what I learn on the journey from code to boardroom."
social-github: "stew-anderson"
social-linkedin: "stewart-anderson-095bb634"
analytics: "G-GWQ326R86E"
markdown: "kramdown"
plugins:
  - "jekyll-sitemap"
  - "jekyll-paginate"
  - "jemoji"
  - "jekyll-feed"
paginate: 8
paginate_path: "/page/:num"
feed:
  icon: "/assets/img/favicon/apple-touch-icon.png"
  tags: true
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]